name: CI

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Update Polywrap Nodes on development server
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_HOST_DEVELOP }}
          username: ${{ secrets.SSH_USERNAME_DEVELOP }}
          key: ${{ secrets.DEPLOYMENT_KEY_DEVELOP }}
          port: 22
          script: |
            export PATH="$PATH:/home/***/.nvm/versions/node/v16.13.0/bin/"
            git -C /home/ubuntu/polywrap/nodes fetch origin
            git -C /home/ubuntu/polywrap/nodes checkout "${GITHUB_SHA}"
            curl -o- https://raw.githubusercontent.com/nerfZael/persistence-scripts/main/update.sh | bash
