name: CI

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Update Polywrap Nodes on development server
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_HOST_DEVELOP }}
          username: ${{ secrets.SSH_USERNAME_DEVELOP }}
          key: ${{ secrets.DEPLOYMENT_KEY_DEVELOP }}
          port: 22
          script: |
            export NVM_DIR=$HOME/.nvm;
            source $NVM_DIR/nvm.sh;

            cd /home/ubuntu/polywrap/nodes/persistence-node
            nvm install && nvm use

            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            echo "export PATH=~/.npm-global/bin:\$PATH" >> ~/.profile
            source ~/.profile

            git -C /home/ubuntu/polywrap/nodes fetch origin
            git -C /home/ubuntu/polywrap/nodes checkout develop
            git -C /home/ubuntu/polywrap/nodes pull
            pm2 delete all
            cd /home/ubuntu/polywrap/nodes/nodes/persistence-node
            yarn
            yarn build
            curl -o- https://raw.githubusercontent.com/nerfZael/persistence-scripts/main/.env > .env

            pm2 start ipfs --max-memory-restart 900M -- daemon
            node bin/main.js past -b 500000 --log
            pm2 start bin/main.js -- daemon --http 8081 --log

            pm2 startup
            sudo env PATH=$PATH:/home/ubuntu/.nvm/versions/node/v16.13.0/bin /home/ubuntu/.npm-global/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu

            pm2 save