name: CI

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install:ci

      - name: Build
        run: yarn build
        
      - name: "Copy persistence node build artifacts to development server"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEVELOP }}
          username: ${{ secrets.SSH_USERNAME_DEVELOP }}
          key: ${{ secrets.DEPLOYMENT_KEY_DEVELOP }}
          port: 22
          source: "./nodes/persistence-node/bin"
          target: "/home/ubuntu/staging/polywrap/nodes"

      - name: "Copy ENS indexer node artifacts to development server"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEVELOP }}
          username: ${{ secrets.SSH_USERNAME_DEVELOP }}
          key: ${{ secrets.DEPLOYMENT_KEY_DEVELOP }}
          port: 22
          source: "./nodes/ens-contenthash-indexer-node/bin"
          target: "/home/ubuntu/staging/polywrap/nodes"

      - name: "Copy persistence node node_modules to development server"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEVELOP }}
          username: ${{ secrets.SSH_USERNAME_DEVELOP }}
          key: ${{ secrets.DEPLOYMENT_KEY_DEVELOP }}
          port: 22
          source: "./nodes/persistence-node/node_modules"
          target: "/home/ubuntu/staging/polywrap/nodes"

        
      - name: "Copy ENS indexer node node_modules to development server"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEVELOP }}
          username: ${{ secrets.SSH_USERNAME_DEVELOP }}
          key: ${{ secrets.DEPLOYMENT_KEY_DEVELOP }}
          port: 22
          source: "./nodes/ens-contenthash-indexer-node/node_modules"
          target: "/home/ubuntu/staging/polywrap/nodes"

      - name: Deploy nodes to development server
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST_DEVELOP }}
            username: ${{ secrets.SSH_USERNAME_DEVELOP }}
            key: ${{ secrets.DEPLOYMENT_KEY_DEVELOP }}
            port: 22
            script: |
              export NVM_DIR=$HOME/.nvm;
              source $NVM_DIR/nvm.sh;

              mkdir ~/.npm-global
              npm config set prefix '~/.npm-global'
              echo "export PATH=~/.npm-global/bin:\$PATH" >> ~/.profile
              source ~/.profile

              set -e

              cd /home/ubuntu/hosting/polywrap/nodes/nodes/persistence-node
              cp -r /home/ubuntu/staging/polywrap/nodes/nodes/persistence-node/bin ./
              cp -r /home/ubuntu/staging/polywrap/nodes/nodes/persistence-node/node_modules ./

              cd /home/ubuntu/hosting/polywrap/nodes/nodes/ens-contenthash-indexer-node
              cp -r /home/ubuntu/staging/polywrap/nodes/nodes/ens-contenthash-indexer-node/bin ./
              cp -r /home/ubuntu/staging/polywrap/nodes/nodes/ens-contenthash-indexer-node/node_modules ./

              curl -o- https://raw.githubusercontent.com/nerfZael/persistence-scripts/main/.env > .env

              node /home/ubuntu/hosting/polywrap/nodes/nodes/ens-contenthash-indexer-node/bin/main.js init --data ./.data/rinkeby --log
              node /home/ubuntu/hosting/polywrap/nodes/nodes/ens-contenthash-indexer-node/bin/main.js init --data ./.data/ropsten --log
            
              node /home/ubuntu/hosting/polywrap/nodes/nodes/persistence-node/bin/main.js init --data ./.data --log
              
              pm2 start /home/ubuntu/hosting/polywrap/nodes/nodes/ens-contenthash-indexer-node/bin/main.js --name ens-indexer-node-rinkeby -- daemon --data ./.data/rinkeby --port 8082 --log --from-block 10470682 --log
              pm2 start /home/ubuntu/hosting/polywrap/nodes/nodes/ens-contenthash-indexer-node/bin/main.js --name ens-indexer-node-ropsten -- daemon --data ./.data/ropsten --port 8083 --log --from-block 10470682 --log

              pm2 start /home/ubuntu/hosting/polywrap/nodes/nodes/persistence-node/bin/main.js --name persistence-node -- daemon --data ./.data --http 8081 --log

              sudo env PATH=$PATH:/home/ubuntu/.nvm/versions/node/v16.13.0/bin /home/ubuntu/.npm-global/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu

              pm2 save